CREATE DATABASE IF NOT EXISTS cold_chain_logistics;
USE cold_chain_logistics;

CREATE TABLE IF NOT EXISTS reefers (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100),
    carrier VARCHAR(100),
    rigId VARCHAR(50),
    status ENUM('critical', 'optimal', 'warning', 'ultracold'),
    statusLabel VARCHAR(50),
    temp DECIMAL(5,2),
    targetTemp DECIMAL(5,2),
    tolerance DECIMAL(5,2),
    cargo VARCHAR(200),
    doorStatus ENUM('SEALED', 'UNSEALED'),
    corridor VARCHAR(100),
    statusDetail VARCHAR(255),
    trajectoryText VARCHAR(100),
    trajectoryTrend ENUM('up', 'stable', 'down'),
    specs JSON,
    sparklineData JSON
);

CREATE TABLE IF NOT EXISTS excursion_incidents (
    id VARCHAR(50) PRIMARY KEY,
    reeferId VARCHAR(50),
    client VARCHAR(100),
    cargoLot VARCHAR(100),
    thermalPeak VARCHAR(50),
    thermalVariance VARCHAR(50),
    duration VARCHAR(50),
    resolutionVerdict VARCHAR(100),
    statusStyle ENUM('error', 'surface', 'neutral'),
    claimValue VARCHAR(50),
    penaltyValue VARCHAR(50),
    notes TEXT
);

CREATE TABLE IF NOT EXISTS customer_invoices (
    id VARCHAR(50) PRIMARY KEY,
    date DATE,
    client VARCHAR(100),
    corridor VARCHAR(100),
    corridorIcon VARCHAR(50),
    orderRef VARCHAR(50),
    grossFreight DECIMAL(12,2),
    gxpDeductions DECIMAL(12,2),
    incidentRef VARCHAR(50),
    netPayable DECIMAL(12,2),
    paymentStatus ENUM('pending', 'paid', 'sent'),
    paymentStatusLabel VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS vendor_bills (
    id VARCHAR(50) PRIMARY KEY,
    vendorName VARCHAR(100),
    vendorId VARCHAR(50),
    amount DECIMAL(12,2),
    status VARCHAR(50),
    description TEXT,
    purchaseOrder VARCHAR(50),
    disbursementLedger VARCHAR(50),
    warrantyToken VARCHAR(50),
    terms VARCHAR(100),
    targetAsset VARCHAR(50),
    serviceLocation VARCHAR(100),
    paid BOOLEAN
);

CREATE TABLE IF NOT EXISTS journal_entries (
    id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(150),
    date VARCHAR(50),
    autoPosted BOOLEAN,
    note TEXT,
    totalCheck DECIMAL(12,2)
);

CREATE TABLE IF NOT EXISTS journal_entry_lines (
    id INT AUTO_INCREMENT PRIMARY KEY,
    journalEntryId VARCHAR(50),
    accountCode VARCHAR(20),
    accountTitle VARCHAR(100),
    entityRef VARCHAR(100),
    debit DECIMAL(12,2) DEFAULT NULL,
    credit DECIMAL(12,2) DEFAULT NULL,
    highlight BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (journalEntryId) REFERENCES journal_entries(id) ON DELETE CASCADE
);


-- Mock Data Generation

INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-5922', 'Container #RC-5922', 'ColdWave Express', 'Rig #942', 'critical', 'CRITICAL', -12.06, -20.00, 2.50, 'Moderna Therapeutics #MD-220', 'SEALED', 'Pacific Biotech Run', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-2116', 'Container #RC-2116', 'ThermoTrans Logistics LLC', 'Rig #976', 'warning', 'WARNING', -21.00, -20.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'Pacific Biotech Run', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-7262', 'Container #RC-7262', 'CryoShip Inc.', 'Rig #503', 'ultracold', 'ULTRACOLD', -72.03, -75.00, 2.50, 'Pfizer mRNA Batch #VN-88210', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-6457', 'Container #RC-6457', 'CryoShip Inc.', 'Rig #212', 'optimal', 'OPTIMAL', -18.26, -20.00, 2.50, 'Pfizer mRNA Batch #VN-88210', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-8490', 'Container #RC-8490', 'ThermoTrans Logistics LLC', 'Rig #388', 'ultracold', 'ULTRACOLD', -74.86, -75.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-7572', 'Container #RC-7572', 'ThermoTrans Logistics LLC', 'Rig #242', 'ultracold', 'ULTRACOLD', -77.40, -75.00, 2.50, 'Pfizer mRNA Batch #VN-88210', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-3717', 'Container #RC-3717', 'ThermoTrans Logistics LLC', 'Rig #319', 'critical', 'CRITICAL', -11.22, -20.00, 2.50, 'Pfizer mRNA Batch #VN-88210', 'SEALED', 'North-South Vaccine Route', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-9738', 'Container #RC-9738', 'ThermoTrans Logistics LLC', 'Rig #571', 'optimal', 'OPTIMAL', -21.25, -20.00, 2.50, 'Moderna Therapeutics #MD-220', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-5478', 'Container #RC-5478', 'ColdWave Express', 'Rig #693', 'ultracold', 'ULTRACOLD', -72.65, -75.00, 2.50, 'Genentech Labs #GL-40', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-1500', 'Container #RC-1500', 'Polar Freight', 'Rig #905', 'optimal', 'OPTIMAL', -18.88, -20.00, 2.50, 'Moderna Therapeutics #MD-220', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-5504', 'Container #RC-5504', 'ColdWave Express', 'Rig #423', 'critical', 'CRITICAL', -5.62, -20.00, 2.50, 'Pfizer mRNA Batch #VN-88210', 'SEALED', 'Pacific Biotech Run', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-1621', 'Container #RC-1621', 'ColdWave Express', 'Rig #776', 'ultracold', 'ULTRACOLD', -72.74, -75.00, 2.50, 'Novartis Global #NV-100', 'SEALED', 'North-South Vaccine Route', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-2173', 'Container #RC-2173', 'ThermoTrans Logistics LLC', 'Rig #288', 'optimal', 'OPTIMAL', -18.57, -20.00, 2.50, 'Moderna Therapeutics #MD-220', 'SEALED', 'Oxford-Frankfurt Cryo', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-2725', 'Container #RC-2725', 'Polar Freight', 'Rig #230', 'optimal', 'OPTIMAL', -21.95, -20.00, 2.50, 'Pfizer mRNA Batch #VN-88210', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-3545', 'Container #RC-3545', 'ThermoTrans Logistics LLC', 'Rig #750', 'optimal', 'OPTIMAL', -20.70, -20.00, 2.50, 'Moderna Therapeutics #MD-220', 'SEALED', 'Pacific Biotech Run', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-3276', 'Container #RC-3276', 'Polar Freight', 'Rig #327', 'ultracold', 'ULTRACOLD', -74.89, -75.00, 2.50, 'Novartis Global #NV-100', 'SEALED', 'Pacific Biotech Run', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-4471', 'Container #RC-4471', 'ColdWave Express', 'Rig #186', 'ultracold', 'ULTRACOLD', -75.30, -75.00, 2.50, 'Moderna Therapeutics #MD-220', 'SEALED', 'Pacific Biotech Run', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-8691', 'Container #RC-8691', 'ThermoTrans Logistics LLC', 'Rig #205', 'optimal', 'OPTIMAL', -19.66, -20.00, 2.50, 'Moderna Therapeutics #MD-220', 'SEALED', 'North-South Vaccine Route', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-4019', 'Container #RC-4019', 'ColdWave Express', 'Rig #304', 'warning', 'WARNING', -20.96, -20.00, 2.50, 'Pfizer mRNA Batch #VN-88210', 'SEALED', 'Pacific Biotech Run', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-7984', 'Container #RC-7984', 'ColdWave Express', 'Rig #632', 'critical', 'CRITICAL', -8.45, -20.00, 2.50, 'Genentech Labs #GL-40', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-3450', 'Container #RC-3450', 'CryoShip Inc.', 'Rig #648', 'warning', 'WARNING', -18.76, -20.00, 2.50, 'Genentech Labs #GL-40', 'SEALED', 'Pacific Biotech Run', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-3449', 'Container #RC-3449', 'CryoShip Inc.', 'Rig #994', 'warning', 'WARNING', -18.09, -20.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'Oxford-Frankfurt Cryo', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-2967', 'Container #RC-2967', 'ColdWave Express', 'Rig #348', 'warning', 'WARNING', -21.78, -20.00, 2.50, 'Novartis Global #NV-100', 'SEALED', 'Oxford-Frankfurt Cryo', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-3682', 'Container #RC-3682', 'ColdWave Express', 'Rig #811', 'warning', 'WARNING', -21.45, -20.00, 2.50, 'Genentech Labs #GL-40', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-2598', 'Container #RC-2598', 'ThermoTrans Logistics LLC', 'Rig #230', 'warning', 'WARNING', -21.09, -20.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'North-South Vaccine Route', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-4961', 'Container #RC-4961', 'CryoShip Inc.', 'Rig #932', 'critical', 'CRITICAL', -6.66, -20.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-7923', 'Container #RC-7923', 'ThermoTrans Logistics LLC', 'Rig #613', 'critical', 'CRITICAL', -14.40, -20.00, 2.50, 'Genentech Labs #GL-40', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-9374', 'Container #RC-9374', 'ColdWave Express', 'Rig #262', 'ultracold', 'ULTRACOLD', -71.63, -75.00, 2.50, 'Pfizer mRNA Batch #VN-88210', 'SEALED', 'North-South Vaccine Route', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-8079', 'Container #RC-8079', 'ThermoTrans Logistics LLC', 'Rig #785', 'ultracold', 'ULTRACOLD', -76.20, -75.00, 2.50, 'Moderna Therapeutics #MD-220', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-1359', 'Container #RC-1359', 'Polar Freight', 'Rig #485', 'critical', 'CRITICAL', -10.36, -20.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'Oxford-Frankfurt Cryo', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-2429', 'Container #RC-2429', 'ThermoTrans Logistics LLC', 'Rig #722', 'critical', 'CRITICAL', -8.17, -20.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'North-South Vaccine Route', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-1266', 'Container #RC-1266', 'CryoShip Inc.', 'Rig #396', 'ultracold', 'ULTRACOLD', -76.49, -75.00, 2.50, 'Genentech Labs #GL-40', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-1004', 'Container #RC-1004', 'ColdWave Express', 'Rig #489', 'optimal', 'OPTIMAL', -18.24, -20.00, 2.50, 'Genentech Labs #GL-40', 'SEALED', 'Pacific Biotech Run', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-3932', 'Container #RC-3932', 'Polar Freight', 'Rig #125', 'optimal', 'OPTIMAL', -19.47, -20.00, 2.50, 'Pfizer mRNA Batch #VN-88210', 'SEALED', 'Pacific Biotech Run', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-1156', 'Container #RC-1156', 'CryoShip Inc.', 'Rig #344', 'optimal', 'OPTIMAL', -18.55, -20.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'Oxford-Frankfurt Cryo', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-2685', 'Container #RC-2685', 'CryoShip Inc.', 'Rig #127', 'optimal', 'OPTIMAL', -18.66, -20.00, 2.50, 'Genentech Labs #GL-40', 'SEALED', 'Oxford-Frankfurt Cryo', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-7328', 'Container #RC-7328', 'CryoShip Inc.', 'Rig #540', 'optimal', 'OPTIMAL', -20.41, -20.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'North-South Vaccine Route', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-9528', 'Container #RC-9528', 'ColdWave Express', 'Rig #675', 'critical', 'CRITICAL', -14.27, -20.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-1808', 'Container #RC-1808', 'ThermoTrans Logistics LLC', 'Rig #558', 'critical', 'CRITICAL', -10.88, -20.00, 2.50, 'Moderna Therapeutics #MD-220', 'SEALED', 'Pacific Biotech Run', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-4719', 'Container #RC-4719', 'ColdWave Express', 'Rig #355', 'ultracold', 'ULTRACOLD', -78.53, -75.00, 2.50, 'Novartis Global #NV-100', 'SEALED', 'Oxford-Frankfurt Cryo', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-9035', 'Container #RC-9035', 'ColdWave Express', 'Rig #579', 'optimal', 'OPTIMAL', -18.66, -20.00, 2.50, 'Moderna Therapeutics #MD-220', 'SEALED', 'North-South Vaccine Route', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-3046', 'Container #RC-3046', 'CryoShip Inc.', 'Rig #581', 'warning', 'WARNING', -18.10, -20.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'Transatlantic Air Direct', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-3500', 'Container #RC-3500', 'Polar Freight', 'Rig #427', 'ultracold', 'ULTRACOLD', -76.89, -75.00, 2.50, 'Novartis Global #NV-100', 'SEALED', 'Oxford-Frankfurt Cryo', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-4308', 'Container #RC-4308', 'ColdWave Express', 'Rig #708', 'warning', 'WARNING', -18.45, -20.00, 2.50, 'Sanofi Pasteur #SP-10', 'SEALED', 'North-South Vaccine Route', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');
INSERT INTO reefers (id, name, carrier, rigId, status, statusLabel, temp, targetTemp, tolerance, cargo, doorStatus, corridor, statusDetail, trajectoryText, trajectoryTrend, specs, sparklineData) VALUES ('#RC-2437', 'Container #RC-2437', 'ThermoTrans Logistics LLC', 'Rig #992', 'critical', 'CRITICAL', -12.46, -20.00, 2.50, 'Novartis Global #NV-100', 'SEALED', 'Oxford-Frankfurt Cryo', 'Tracking Active', 'Trend Stable', 'stable', '{}', '[]');

INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-6913', '#RC-3276', 'BioPharma Inc', 'Pfizer mRNA Batch #VN-88210', '-13.2°C', '+1.8°C', '24 min', 'RESOLVED', 'neutral', '$50,000', 'Penalty: $3,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-1747', '#RC-5504', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '33 min', 'RESOLVED', 'neutral', '$11,000', 'Penalty: $2,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-4681', '#RC-3717', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '41 min', 'RESOLVED', 'neutral', '$48,000', 'Penalty: $2,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-3152', '#RC-8490', 'BioPharma Inc', 'Novartis Global #NV-100', '-13.2°C', '+1.8°C', '7 min', 'RESOLVED', 'neutral', '$20,000', 'Penalty: $3,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-3380', '#RC-2967', 'BioPharma Inc', 'Pfizer mRNA Batch #VN-88210', '-13.2°C', '+1.8°C', '24 min', 'RESOLVED', 'neutral', '$40,000', 'Penalty: $3,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-1390', '#RC-1359', 'BioPharma Inc', 'Sanofi Pasteur #SP-10', '-13.2°C', '+1.8°C', '37 min', 'RESOLVED', 'neutral', '$22,000', 'Penalty: $4,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-8392', '#RC-1156', 'BioPharma Inc', 'Moderna Therapeutics #MD-220', '-13.2°C', '+1.8°C', '44 min', 'RESOLVED', 'neutral', '$22,000', 'Penalty: $4,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-4846', '#RC-3545', 'BioPharma Inc', 'Sanofi Pasteur #SP-10', '-13.2°C', '+1.8°C', '42 min', 'RESOLVED', 'neutral', '$34,000', 'Penalty: $3,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-5436', '#RC-4471', 'BioPharma Inc', 'Pfizer mRNA Batch #VN-88210', '-13.2°C', '+1.8°C', '25 min', 'RESOLVED', 'neutral', '$39,000', 'Penalty: $4,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-9831', '#RC-7328', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '25 min', 'RESOLVED', 'neutral', '$41,000', 'Penalty: $5,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-5562', '#RC-5922', 'BioPharma Inc', 'Moderna Therapeutics #MD-220', '-13.2°C', '+1.8°C', '19 min', 'RESOLVED', 'neutral', '$10,000', 'Penalty: $4,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-6922', '#RC-4961', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '29 min', 'RESOLVED', 'neutral', '$11,000', 'Penalty: $3,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-6371', '#RC-3449', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '6 min', 'RESOLVED', 'neutral', '$18,000', 'Penalty: $3,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-4721', '#RC-1808', 'BioPharma Inc', 'Novartis Global #NV-100', '-13.2°C', '+1.8°C', '33 min', 'RESOLVED', 'neutral', '$39,000', 'Penalty: $2,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-5784', '#RC-3500', 'BioPharma Inc', 'Novartis Global #NV-100', '-13.2°C', '+1.8°C', '40 min', 'RESOLVED', 'neutral', '$32,000', 'Penalty: $3,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-3788', '#RC-9035', 'BioPharma Inc', 'Novartis Global #NV-100', '-13.2°C', '+1.8°C', '31 min', 'RESOLVED', 'neutral', '$30,000', 'Penalty: $5,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-4584', '#RC-3932', 'BioPharma Inc', 'Novartis Global #NV-100', '-13.2°C', '+1.8°C', '23 min', 'RESOLVED', 'neutral', '$32,000', 'Penalty: $2,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-5566', '#RC-8691', 'BioPharma Inc', 'Pfizer mRNA Batch #VN-88210', '-13.2°C', '+1.8°C', '39 min', 'RESOLVED', 'neutral', '$14,000', 'Penalty: $4,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-8596', '#RC-6457', 'BioPharma Inc', 'Sanofi Pasteur #SP-10', '-13.2°C', '+1.8°C', '43 min', 'RESOLVED', 'neutral', '$43,000', 'Penalty: $4,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-7989', '#RC-4719', 'BioPharma Inc', 'Novartis Global #NV-100', '-13.2°C', '+1.8°C', '27 min', 'RESOLVED', 'neutral', '$37,000', 'Penalty: $3,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-4250', '#RC-8490', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '44 min', 'RESOLVED', 'neutral', '$36,000', 'Penalty: $5,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-9567', '#RC-3932', 'BioPharma Inc', 'Novartis Global #NV-100', '-13.2°C', '+1.8°C', '27 min', 'RESOLVED', 'neutral', '$48,000', 'Penalty: $2,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-7532', '#RC-9035', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '27 min', 'RESOLVED', 'neutral', '$10,000', 'Penalty: $4,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-2655', '#RC-9374', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '9 min', 'RESOLVED', 'neutral', '$28,000', 'Penalty: $2,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-4536', '#RC-7923', 'BioPharma Inc', 'Pfizer mRNA Batch #VN-88210', '-13.2°C', '+1.8°C', '20 min', 'RESOLVED', 'neutral', '$35,000', 'Penalty: $2,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-1366', '#RC-2116', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '11 min', 'RESOLVED', 'neutral', '$20,000', 'Penalty: $2,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-7292', '#RC-3449', 'BioPharma Inc', 'Sanofi Pasteur #SP-10', '-13.2°C', '+1.8°C', '35 min', 'RESOLVED', 'neutral', '$10,000', 'Penalty: $5,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-3276', '#RC-5478', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '38 min', 'RESOLVED', 'neutral', '$47,000', 'Penalty: $5,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-3302', '#RC-1266', 'BioPharma Inc', 'Novartis Global #NV-100', '-13.2°C', '+1.8°C', '36 min', 'RESOLVED', 'neutral', '$33,000', 'Penalty: $5,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-1158', '#RC-2116', 'BioPharma Inc', 'Sanofi Pasteur #SP-10', '-13.2°C', '+1.8°C', '6 min', 'RESOLVED', 'neutral', '$42,000', 'Penalty: $2,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-2252', '#RC-2173', 'BioPharma Inc', 'Sanofi Pasteur #SP-10', '-13.2°C', '+1.8°C', '25 min', 'RESOLVED', 'neutral', '$37,000', 'Penalty: $2,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-4240', '#RC-9374', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '34 min', 'RESOLVED', 'neutral', '$44,000', 'Penalty: $3,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-8346', '#RC-9374', 'BioPharma Inc', 'Sanofi Pasteur #SP-10', '-13.2°C', '+1.8°C', '15 min', 'RESOLVED', 'neutral', '$29,000', 'Penalty: $2,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-5045', '#RC-3276', 'BioPharma Inc', 'Sanofi Pasteur #SP-10', '-13.2°C', '+1.8°C', '41 min', 'RESOLVED', 'neutral', '$34,000', 'Penalty: $1,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-2022', '#RC-4961', 'BioPharma Inc', 'Moderna Therapeutics #MD-220', '-13.2°C', '+1.8°C', '9 min', 'RESOLVED', 'neutral', '$13,000', 'Penalty: $5,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-4809', '#RC-2173', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '21 min', 'RESOLVED', 'neutral', '$30,000', 'Penalty: $3,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-1843', '#RC-9738', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '31 min', 'RESOLVED', 'neutral', '$21,000', 'Penalty: $4,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-1295', '#RC-2437', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '5 min', 'RESOLVED', 'neutral', '$25,000', 'Penalty: $4,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-5661', '#RC-2685', 'BioPharma Inc', 'Sanofi Pasteur #SP-10', '-13.2°C', '+1.8°C', '20 min', 'RESOLVED', 'neutral', '$28,000', 'Penalty: $1,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-7810', '#RC-9035', 'BioPharma Inc', 'Genentech Labs #GL-40', '-13.2°C', '+1.8°C', '26 min', 'RESOLVED', 'neutral', '$15,000', 'Penalty: $4,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-5728', '#RC-3932', 'BioPharma Inc', 'Novartis Global #NV-100', '-13.2°C', '+1.8°C', '26 min', 'RESOLVED', 'neutral', '$14,000', 'Penalty: $5,000', 'Automated log');
INSERT INTO excursion_incidents (id, reeferId, client, cargoLot, thermalPeak, thermalVariance, duration, resolutionVerdict, statusStyle, claimValue, penaltyValue, notes) VALUES ('#EXC-8789', '#RC-4961', 'BioPharma Inc', 'Moderna Therapeutics #MD-220', '-13.2°C', '+1.8°C', '17 min', 'RESOLVED', 'neutral', '$41,000', 'Penalty: $5,000', 'Automated log');

INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0400', '2025-09-09', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9920', 36162.00, 0.00, NULL, 36162.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0401', '2025-09-27', 'Global Pharma', 'Pacific Biotech Run', 'flight_takeoff', 'SO-9921', 22454.00, 0.00, NULL, 22454.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0402', '2025-09-10', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9922', 19634.00, -2465.00, NULL, 17169.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0403', '2025-09-12', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9923', 28235.00, -1076.00, NULL, 27159.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0404', '2025-09-21', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9924', 27090.00, 0.00, NULL, 27090.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0405', '2025-09-13', 'Global Pharma', 'North-South Vaccine Route', 'flight_takeoff', 'SO-9925', 39056.00, 0.00, NULL, 39056.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0406', '2025-09-09', 'Global Pharma', 'North-South Vaccine Route', 'flight_takeoff', 'SO-9926', 30707.00, 0.00, NULL, 30707.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0407', '2025-09-01', 'Global Pharma', 'North-South Vaccine Route', 'flight_takeoff', 'SO-9927', 29127.00, 0.00, NULL, 29127.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0408', '2025-09-15', 'Global Pharma', 'Pacific Biotech Run', 'flight_takeoff', 'SO-9928', 24834.00, 0.00, NULL, 24834.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0409', '2025-09-11', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9929', 35724.00, 0.00, NULL, 35724.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0410', '2025-09-13', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9930', 44477.00, 0.00, NULL, 44477.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0411', '2025-09-24', 'Global Pharma', 'Pacific Biotech Run', 'flight_takeoff', 'SO-9931', 32048.00, 0.00, NULL, 32048.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0412', '2025-09-16', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9932', 40061.00, 0.00, NULL, 40061.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0413', '2025-09-16', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9933', 16134.00, 0.00, NULL, 16134.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0414', '2025-09-02', 'Global Pharma', 'North-South Vaccine Route', 'flight_takeoff', 'SO-9934', 26491.00, 0.00, NULL, 26491.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0415', '2025-09-15', 'Global Pharma', 'Pacific Biotech Run', 'flight_takeoff', 'SO-9935', 30711.00, 0.00, NULL, 30711.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0416', '2025-09-22', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9936', 25487.00, 0.00, NULL, 25487.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0417', '2025-09-21', 'Global Pharma', 'North-South Vaccine Route', 'flight_takeoff', 'SO-9937', 17190.00, -4177.00, NULL, 13013.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0418', '2025-09-25', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9938', 38637.00, 0.00, NULL, 38637.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0419', '2025-09-26', 'Global Pharma', 'Pacific Biotech Run', 'flight_takeoff', 'SO-9939', 30021.00, 0.00, NULL, 30021.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0420', '2025-09-04', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9940', 40417.00, -2212.00, NULL, 38205.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0421', '2025-09-18', 'Global Pharma', 'Pacific Biotech Run', 'flight_takeoff', 'SO-9941', 36374.00, 0.00, NULL, 36374.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0422', '2025-09-28', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9942', 43918.00, 0.00, NULL, 43918.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0423', '2025-09-20', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9943', 24024.00, -1759.00, NULL, 22265.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0424', '2025-09-10', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9944', 19369.00, 0.00, NULL, 19369.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0425', '2025-09-01', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9945', 39427.00, 0.00, NULL, 39427.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0426', '2025-09-02', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9946', 30239.00, 0.00, NULL, 30239.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0427', '2025-09-19', 'Global Pharma', 'North-South Vaccine Route', 'flight_takeoff', 'SO-9947', 17247.00, 0.00, NULL, 17247.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0428', '2025-09-02', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9948', 15261.00, 0.00, NULL, 15261.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0429', '2025-09-22', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9949', 39467.00, 0.00, NULL, 39467.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0430', '2025-09-14', 'Global Pharma', 'North-South Vaccine Route', 'flight_takeoff', 'SO-9950', 21322.00, 0.00, NULL, 21322.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0431', '2025-09-02', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9951', 20170.00, -2101.00, NULL, 18069.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0432', '2025-09-24', 'Global Pharma', 'Pacific Biotech Run', 'flight_takeoff', 'SO-9952', 36556.00, 0.00, NULL, 36556.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0433', '2025-09-01', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9953', 17089.00, 0.00, NULL, 17089.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0434', '2025-09-20', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9954', 34949.00, 0.00, NULL, 34949.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0435', '2025-09-01', 'Global Pharma', 'North-South Vaccine Route', 'flight_takeoff', 'SO-9955', 25002.00, -1970.00, NULL, 23032.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0436', '2025-09-07', 'Global Pharma', 'Pacific Biotech Run', 'flight_takeoff', 'SO-9956', 19410.00, 0.00, NULL, 19410.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0437', '2025-09-04', 'Global Pharma', 'North-South Vaccine Route', 'flight_takeoff', 'SO-9957', 31941.00, 0.00, NULL, 31941.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0438', '2025-09-01', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9958', 29035.00, 0.00, NULL, 29035.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0439', '2025-09-27', 'Global Pharma', 'Transatlantic Air Direct', 'flight_takeoff', 'SO-9959', 43901.00, 0.00, NULL, 43901.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0440', '2025-09-23', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9960', 30230.00, 0.00, NULL, 30230.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0441', '2025-09-27', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9961', 39500.00, 0.00, NULL, 39500.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0442', '2025-09-01', 'Global Pharma', 'Oxford-Frankfurt Cryo', 'flight_takeoff', 'SO-9962', 30158.00, 0.00, NULL, 30158.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0443', '2025-09-28', 'Global Pharma', 'North-South Vaccine Route', 'flight_takeoff', 'SO-9963', 41020.00, 0.00, NULL, 41020.00, 'paid', 'PAID IN FULL');
INSERT INTO customer_invoices (id, date, client, corridor, corridorIcon, orderRef, grossFreight, gxpDeductions, incidentRef, netPayable, paymentStatus, paymentStatusLabel) VALUES ('INV-2025-0444', '2025-09-27', 'Global Pharma', 'North-South Vaccine Route', 'flight_takeoff', 'SO-9964', 19374.00, -1198.00, NULL, 18176.00, 'paid', 'PAID IN FULL');

INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0800', 'ColdWave Express', 'VND-665', 2636.00, 'Disbursed', 'Fleet logistics transport services', 'PO-7849', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0801', 'ThermoTrans Logistics LLC', 'VND-122', 13613.00, 'Disbursed', 'Fleet logistics transport services', 'PO-7715', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0802', 'ThermoTrans Logistics LLC', 'VND-190', 9975.00, 'Disbursed', 'Fleet logistics transport services', 'PO-8423', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0803', 'Polar Freight', 'VND-835', 9961.00, 'Disbursed', 'Fleet logistics transport services', 'PO-8787', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0804', 'ThermoTrans Logistics LLC', 'VND-906', 11181.00, 'Disbursed', 'Fleet logistics transport services', 'PO-8577', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0805', 'ColdWave Express', 'VND-372', 8836.00, 'Disbursed', 'Fleet logistics transport services', 'PO-6711', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0806', 'ColdWave Express', 'VND-570', 2293.00, 'Disbursed', 'Fleet logistics transport services', 'PO-5481', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0807', 'Polar Freight', 'VND-368', 8216.00, 'Disbursed', 'Fleet logistics transport services', 'PO-5039', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0808', 'ThermoTrans Logistics LLC', 'VND-412', 6438.00, 'Disbursed', 'Fleet logistics transport services', 'PO-4558', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0809', 'Polar Freight', 'VND-496', 6674.00, 'Disbursed', 'Fleet logistics transport services', 'PO-4329', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0810', 'Polar Freight', 'VND-123', 3028.00, 'Disbursed', 'Fleet logistics transport services', 'PO-9234', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0811', 'CryoShip Inc.', 'VND-971', 12290.00, 'Disbursed', 'Fleet logistics transport services', 'PO-9156', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0812', 'ThermoTrans Logistics LLC', 'VND-181', 14209.00, 'Disbursed', 'Fleet logistics transport services', 'PO-8519', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0813', 'CryoShip Inc.', 'VND-544', 7936.00, 'Disbursed', 'Fleet logistics transport services', 'PO-6229', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0814', 'ColdWave Express', 'VND-824', 11770.00, 'Disbursed', 'Fleet logistics transport services', 'PO-3829', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0815', 'ThermoTrans Logistics LLC', 'VND-590', 2228.00, 'Disbursed', 'Fleet logistics transport services', 'PO-2740', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0816', 'ColdWave Express', 'VND-216', 8806.00, 'Disbursed', 'Fleet logistics transport services', 'PO-8319', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0817', 'CryoShip Inc.', 'VND-505', 3671.00, 'Disbursed', 'Fleet logistics transport services', 'PO-2769', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0818', 'ColdWave Express', 'VND-845', 8246.00, 'Disbursed', 'Fleet logistics transport services', 'PO-6917', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0819', 'Polar Freight', 'VND-593', 8805.00, 'Disbursed', 'Fleet logistics transport services', 'PO-7777', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0820', 'Polar Freight', 'VND-815', 8901.00, 'Disbursed', 'Fleet logistics transport services', 'PO-4071', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0821', 'Polar Freight', 'VND-155', 11500.00, 'Disbursed', 'Fleet logistics transport services', 'PO-6128', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0822', 'CryoShip Inc.', 'VND-214', 8881.00, 'Disbursed', 'Fleet logistics transport services', 'PO-1440', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0823', 'ColdWave Express', 'VND-417', 7418.00, 'Disbursed', 'Fleet logistics transport services', 'PO-8009', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0824', 'ColdWave Express', 'VND-164', 3737.00, 'Disbursed', 'Fleet logistics transport services', 'PO-8166', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0825', 'ColdWave Express', 'VND-984', 2420.00, 'Disbursed', 'Fleet logistics transport services', 'PO-8621', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0826', 'Polar Freight', 'VND-552', 13521.00, 'Disbursed', 'Fleet logistics transport services', 'PO-3209', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0827', 'ColdWave Express', 'VND-448', 5401.00, 'Disbursed', 'Fleet logistics transport services', 'PO-8387', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0828', 'ColdWave Express', 'VND-752', 4145.00, 'Disbursed', 'Fleet logistics transport services', 'PO-6163', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0829', 'CryoShip Inc.', 'VND-823', 11756.00, 'Disbursed', 'Fleet logistics transport services', 'PO-3764', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0830', 'Polar Freight', 'VND-985', 11619.00, 'Disbursed', 'Fleet logistics transport services', 'PO-9668', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0831', 'Polar Freight', 'VND-221', 3221.00, 'Disbursed', 'Fleet logistics transport services', 'PO-8306', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0832', 'Polar Freight', 'VND-422', 12514.00, 'Disbursed', 'Fleet logistics transport services', 'PO-1826', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0833', 'ThermoTrans Logistics LLC', 'VND-860', 10344.00, 'Disbursed', 'Fleet logistics transport services', 'PO-2359', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0834', 'Polar Freight', 'VND-164', 6214.00, 'Disbursed', 'Fleet logistics transport services', 'PO-1989', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0835', 'ThermoTrans Logistics LLC', 'VND-427', 7916.00, 'Disbursed', 'Fleet logistics transport services', 'PO-3001', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0836', 'Polar Freight', 'VND-336', 3688.00, 'Disbursed', 'Fleet logistics transport services', 'PO-1945', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0837', 'ThermoTrans Logistics LLC', 'VND-958', 4891.00, 'Disbursed', 'Fleet logistics transport services', 'PO-7161', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0838', 'Polar Freight', 'VND-500', 5914.00, 'Disbursed', 'Fleet logistics transport services', 'PO-8020', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);
INSERT INTO vendor_bills (id, vendorName, vendorId, amount, status, description, purchaseOrder, disbursementLedger, warrantyToken, terms, targetAsset, serviceLocation, paid) VALUES ('BILL-2025-0839', 'ColdWave Express', 'VND-811', 12778.00, 'Disbursed', 'Fleet logistics transport services', 'PO-2112', 'Operating Ledger', NULL, 'Net 30', NULL, 'Frankfurt', true);

INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0300', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 27573.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0300', '1100', 'Accounts Receivable', 'Client', 27573.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0300', '4000', 'Freight Revenue', 'OrderRef', NULL, 27573.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0301', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 28058.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0301', '1100', 'Accounts Receivable', 'Client', 28058.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0301', '4000', 'Freight Revenue', 'OrderRef', NULL, 28058.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0302', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 8618.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0302', '1100', 'Accounts Receivable', 'Client', 8618.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0302', '4000', 'Freight Revenue', 'OrderRef', NULL, 8618.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0303', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 22791.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0303', '1100', 'Accounts Receivable', 'Client', 22791.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0303', '4000', 'Freight Revenue', 'OrderRef', NULL, 22791.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0304', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 13759.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0304', '1100', 'Accounts Receivable', 'Client', 13759.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0304', '4000', 'Freight Revenue', 'OrderRef', NULL, 13759.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0305', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 11286.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0305', '1100', 'Accounts Receivable', 'Client', 11286.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0305', '4000', 'Freight Revenue', 'OrderRef', NULL, 11286.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0306', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 14082.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0306', '1100', 'Accounts Receivable', 'Client', 14082.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0306', '4000', 'Freight Revenue', 'OrderRef', NULL, 14082.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0307', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 13922.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0307', '1100', 'Accounts Receivable', 'Client', 13922.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0307', '4000', 'Freight Revenue', 'OrderRef', NULL, 13922.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0308', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 22027.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0308', '1100', 'Accounts Receivable', 'Client', 22027.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0308', '4000', 'Freight Revenue', 'OrderRef', NULL, 22027.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0309', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 25635.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0309', '1100', 'Accounts Receivable', 'Client', 25635.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0309', '4000', 'Freight Revenue', 'OrderRef', NULL, 25635.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0310', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 8290.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0310', '1100', 'Accounts Receivable', 'Client', 8290.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0310', '4000', 'Freight Revenue', 'OrderRef', NULL, 8290.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0311', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 12347.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0311', '1100', 'Accounts Receivable', 'Client', 12347.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0311', '4000', 'Freight Revenue', 'OrderRef', NULL, 12347.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0312', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 9825.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0312', '1100', 'Accounts Receivable', 'Client', 9825.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0312', '4000', 'Freight Revenue', 'OrderRef', NULL, 9825.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0313', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 13031.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0313', '1100', 'Accounts Receivable', 'Client', 13031.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0313', '4000', 'Freight Revenue', 'OrderRef', NULL, 13031.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0314', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 13695.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0314', '1100', 'Accounts Receivable', 'Client', 13695.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0314', '4000', 'Freight Revenue', 'OrderRef', NULL, 13695.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0315', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 15551.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0315', '1100', 'Accounts Receivable', 'Client', 15551.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0315', '4000', 'Freight Revenue', 'OrderRef', NULL, 15551.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0316', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 23509.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0316', '1100', 'Accounts Receivable', 'Client', 23509.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0316', '4000', 'Freight Revenue', 'OrderRef', NULL, 23509.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0317', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 20700.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0317', '1100', 'Accounts Receivable', 'Client', 20700.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0317', '4000', 'Freight Revenue', 'OrderRef', NULL, 20700.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0318', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 19557.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0318', '1100', 'Accounts Receivable', 'Client', 19557.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0318', '4000', 'Freight Revenue', 'OrderRef', NULL, 19557.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0319', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 29874.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0319', '1100', 'Accounts Receivable', 'Client', 29874.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0319', '4000', 'Freight Revenue', 'OrderRef', NULL, 29874.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0320', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 23621.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0320', '1100', 'Accounts Receivable', 'Client', 23621.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0320', '4000', 'Freight Revenue', 'OrderRef', NULL, 23621.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0321', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 19180.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0321', '1100', 'Accounts Receivable', 'Client', 19180.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0321', '4000', 'Freight Revenue', 'OrderRef', NULL, 19180.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0322', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 18475.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0322', '1100', 'Accounts Receivable', 'Client', 18475.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0322', '4000', 'Freight Revenue', 'OrderRef', NULL, 18475.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0323', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 12480.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0323', '1100', 'Accounts Receivable', 'Client', 12480.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0323', '4000', 'Freight Revenue', 'OrderRef', NULL, 12480.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0324', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 12683.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0324', '1100', 'Accounts Receivable', 'Client', 12683.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0324', '4000', 'Freight Revenue', 'OrderRef', NULL, 12683.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0325', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 22140.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0325', '1100', 'Accounts Receivable', 'Client', 22140.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0325', '4000', 'Freight Revenue', 'OrderRef', NULL, 22140.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0326', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 27186.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0326', '1100', 'Accounts Receivable', 'Client', 27186.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0326', '4000', 'Freight Revenue', 'OrderRef', NULL, 27186.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0327', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 6047.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0327', '1100', 'Accounts Receivable', 'Client', 6047.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0327', '4000', 'Freight Revenue', 'OrderRef', NULL, 6047.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0328', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 8902.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0328', '1100', 'Accounts Receivable', 'Client', 8902.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0328', '4000', 'Freight Revenue', 'OrderRef', NULL, 8902.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0329', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 10201.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0329', '1100', 'Accounts Receivable', 'Client', 10201.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0329', '4000', 'Freight Revenue', 'OrderRef', NULL, 10201.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0330', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 17684.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0330', '1100', 'Accounts Receivable', 'Client', 17684.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0330', '4000', 'Freight Revenue', 'OrderRef', NULL, 17684.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0331', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 20313.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0331', '1100', 'Accounts Receivable', 'Client', 20313.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0331', '4000', 'Freight Revenue', 'OrderRef', NULL, 20313.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0332', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 22679.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0332', '1100', 'Accounts Receivable', 'Client', 22679.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0332', '4000', 'Freight Revenue', 'OrderRef', NULL, 22679.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0333', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 24580.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0333', '1100', 'Accounts Receivable', 'Client', 24580.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0333', '4000', 'Freight Revenue', 'OrderRef', NULL, 24580.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0334', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 23630.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0334', '1100', 'Accounts Receivable', 'Client', 23630.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0334', '4000', 'Freight Revenue', 'OrderRef', NULL, 23630.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0335', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 8610.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0335', '1100', 'Accounts Receivable', 'Client', 8610.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0335', '4000', 'Freight Revenue', 'OrderRef', NULL, 8610.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0336', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 17877.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0336', '1100', 'Accounts Receivable', 'Client', 17877.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0336', '4000', 'Freight Revenue', 'OrderRef', NULL, 17877.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0337', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 26316.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0337', '1100', 'Accounts Receivable', 'Client', 26316.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0337', '4000', 'Freight Revenue', 'OrderRef', NULL, 26316.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0338', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 27138.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0338', '1100', 'Accounts Receivable', 'Client', 27138.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0338', '4000', 'Freight Revenue', 'OrderRef', NULL, 27138.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0339', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 15148.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0339', '1100', 'Accounts Receivable', 'Client', 15148.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0339', '4000', 'Freight Revenue', 'OrderRef', NULL, 15148.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0340', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 5632.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0340', '1100', 'Accounts Receivable', 'Client', 5632.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0340', '4000', 'Freight Revenue', 'OrderRef', NULL, 5632.00, false);
INSERT INTO journal_entries (id, title, date, autoPosted, note, totalCheck) VALUES ('JE-2025-0341', 'Automated Freight Accrual', '2025-09-20 14:00 UTC', true, 'System generated', 17376.00);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0341', '1100', 'Accounts Receivable', 'Client', 17376.00, NULL, false);
INSERT INTO journal_entry_lines (journalEntryId, accountCode, accountTitle, entityRef, debit, credit, highlight) VALUES ('JE-2025-0341', '4000', 'Freight Revenue', 'OrderRef', NULL, 17376.00, false);
